[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib", "node_modules"]

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=lib/forge-std/src/"
]
